### ISSUE TITLE
Facebook error on running container

### ISSUE THREAD

**Issue by binaryn3xus** [amadejkastelic/discord-video-embed-bot#1]
Hi, I am getting an error when attempting to start the container...

`docker run -e DISCORD_API_KEY="12bucklemyshoe56pickupsticks78thisisfake" -v /home/joshua/DiscordBot/facebook_cookies.txt:/app/cookies.txt video-embed-bot`

```
Traceback (most recent call last):
  File "/app/main.py", line 11, in <module>
    from downloader import registry
  File "/app/downloader/registry.py", line 2, in <module>
    from downloader import facebook
  File "/app/downloader/facebook.py", line 3, in <module>
    import facebook_scraper
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/facebook_scraper/__init__.py", line 13, in <module>
    from .facebook_scraper import FacebookScraper
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/facebook_scraper/facebook_scraper.py", line 15, in <module>
    from requests_html import HTMLSession
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/requests_html.py", line 14, in <module>
    from lxml.html.clean import Cleaner
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/lxml/html/clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.
```

**Comment by binaryn3xus** [comment]
My image was broken. My fault I believe. Anyway, thanks for this app. Its useful!
